### ISSUE TITLE
Creating a closed election 

### ISSUE THREAD

**Issue by guhur** [MieuxVoter/mvfront-react#10]
Mv-api supports 2 modes of elections : those qualified of opened, in which a user shares a unique link to each voter; and those called closed in which each voter receives a unique link. The latter mode allows to check that each voter casts only one vote. 

In the front end implementation, the closed mode should be triggered by a checkbox. It opens a form to add the email address of each voter.

**Comment by oceanBigOne** [comment]
I think I can take care of front end implementation (or I can help)
