### ISSUE TITLE
Optional opening /closing date of an election 

### ISSUE THREAD

**Issue by guhur** [MieuxVoter/mvfront-react#11]
An election might only start at a very specific time. Similarly it might end only after a precise duration.

On the front end implementation, the user should be able to check an option for opening and closing dates. When the checkbox is checked, 2 calendars and clocks are offered to the user: one for selecting the opening date/time, the second for the closing ones. 

By default, the opening date/time should be left to immediate values. The closing dates to a week later.

**Comment by oceanBigOne** [comment]
I think I can take care of it (or I can help)

**Comment by guhur** [comment]
Solved in #13
