### ISSUE TITLE
Decoralate URL and components

### ISSUE THREAD

**Issue by sebsheep** [MieuxVoter/mvfront-react#12]
Problem: the graphical components such as https://github.com/MieuxVoter/mvfront-react/blob/master/src/components/views/Vote.jsx implicitly depend on the URL through https://github.com/MieuxVoter/mvfront-react/blob/master/src/components/views/Vote.jsx#L83
```        const electionSlug  = this.props.match.params.handle;```
which makes it difficult to understand and hard to scale.

Suggested solution: move all the URL-related manipulations in the Routes component, and add a `electionSlug/token/...` props to the graphical components as well.This way, the behavior of the component is fully determined by its props.

**Comment by sebsheep** [comment]
@oceanBigOne ?

**Comment by oceanBigOne** [comment]
1/ It's not a component, it's a view (page), maybe we should move folder views outside of the components folder.
I think views are not reusables components, they are "specific" of application. So, you can't reuse this view elsewhere even you apply yours suggestion.

2/ It's not not a route of application, which are already in Route component. It's a End-point paths of API, so may-be we should move this path in an other component or config file ?

I agree with you about the difficult to underdanstand and maintain (what if the end-point of API change ..etc...?)

3/ It's not my lines of code :p ... @guhur  what do you think ?

**Comment by oceanBigOne** [comment]
Maybe in .env file ?
`API_ENDPOINTS={ createElection : "/election", ... etc...`

**Comment by oceanBigOne** [comment]
Sorry, I didn't correctly understood what you meant. (I delete my previous message)

I have tried to add props on Routes component but it's not clean and understandable. ([https://tylermcginnis.com/react-router-pass-props-to-components/](https://tylermcginnis.com/react-router-pass-props-to-components/))

**Comment by oceanBigOne** [comment]
@sebsheep , @guhur 

I've been trying to clear things up a little bit...

- Extract slug and params in Routes.jsx
- set all server routes in Routes.jsx
- uniformity of url writing ( with :slug in server routes and app routes )

What do you think?
