### ISSUE TITLE
Impact of not giving a mention to one or more options

### ISSUE THREAD

**Issue by PaulSherp** [MieuxVoter/mvfront-react#53]
### Issue and Steps to Reproduce
Participate in a poll, but leave one or more options without a mention.

#### Actual
There is no indication as to how the fact of not indicating a mention is computed: is there simply no mention attributed or is a mention given by default?

1/ If there is a mention given by default, then participants should be told. In the Orsay experiment, candidates who did not receive a mention were automatically attributed "Rejected", but participants were clearly told ahead of time. "Rejected" also feels like a strong statement for an option that participants simply may not have an opinion about. Maybe "fair" is more appropriate?

2. If there is no mention attributed, then we run the risk of an unknown option placing first without a lot of support (if a few participants strongly support it and no one else has an opinion). In this case, we may want a threshold for the number of mentions given to an option for it to be included in the results.

**Comment by guhur** [comment]
Hi PaulSherp,

The current version of the API does not allow to leave any option without a mention, and so does this user interface.

Implementing this feature is considered for the next version. Rida seems to be in favor of completing the missing mentions with the majority mentions.

**Comment by PaulSherp** [comment]
Thanks for the quick reply! 

This does raise some tricky questions, as this means that participants implicitly give an unknown level of support to an option they do not give a mention to. 

As much as giving "rejected" is a very strong statement, I am not sure that giving the majority mention is the solution: since the majority mention is only known when the results are computed, do we not end up with a situation where the majority mention can be computed with very few results?

I defer to the mathematician here, but -- from an instinctive perspective -- I feel like the middle mention (which, I believe, expresses a neutral opinion, neither positive nor negative) is more appropriate for the case of people who do not have an opinion. Does that make sense?

**Comment by oceanBigOne** [comment]
Hello, giving the majority mention by default after result compute  is a good solution because it doesn't affect the final result.

**Comment by PaulSherp** [comment]
> Hello, giving the majority mention by default after result compute is a good solution because it doesn't affect the final result.

Yes, but they how do we prevent a situation where the majority mention is given by much fewer people than other options?

**Comment by oceanBigOne** [comment]
As I understand it, this has no impact on the final result. The majority mention remains the same

**Comment by oceanBigOne** [comment]
At the first pass of result computing, the majority mention remains the same. Then, if we're tied, we  remove the majority mention to compare others... So it shouldn't have an impact on the end result.

**Comment by PaulSherp** [comment]
We agree that giving the majority mention will not affect the result. But that's quite the point. Let's take a simplified model: voters 1, 2 and 3 assess candidates A, B and C. 
Voter 1 says: excellent, good, good.
Voter 2 says: [blank], very good, excellent.
Voter 3 says: [blank], good, very good.
Unless I am mistaken, if we just attribute a majority mention where there is a blank, then candidate A gets 3 excellent and wins easily, even though two thirds of the voters had no opinion about him/her. I am not sure this is the right way to go, either we should say that at least half of the voters should actively give an opinion, or we should give "fair" (if we think not giving a mention means neither positive nor negative) or "rejected" (if we think that not giving an opinion means you do not support that candidate, as in the Orsay experiment). All three options would seem better than just giving the majority mention, no? I know the example is a simplified model, but it shows the idea and that might well happen for small votes.

**Comment by guhur** [comment]
You are totally right. Filling with the majority mention is not the panacea, but it is the most generic solution though. We can tweak ranking with some sort of quorum, but the solution would be really case-specific.

In this UI, we want to show how simple MJ is, not how flexible the framework is -- that might be another project.

So, if we decide to allow a poll to contain blank votes, we should also nudge the organizers to activate this option in rare cases and avoid offering too many parameters.

**Comment by PaulSherp** [comment]
Fair enough, and, of course, as long as blank voting is not an option, nothing to worry about.

Personally, I actually like that better, as I think it pushes people to form an opinion. But, when discussing compulsory voting in another group, many were adamant that the freedom not to express an opinion was essential, and I think the same people would appreciate being able not to give a mention for some options. 

If that becomes a thing, then I would personally push for "no mention = fair"; to me that's a better option than risking results that lose part of their meaning because of a low number of mentions. This is especially true for small/informal votes, where it becomes quite likely that an option receives way fewer mentions than others (if two out of five people do not give a mention, it the result still really representative?).
